# Generated by Django 5.0.13 on 2025-10-03 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Active products',
            },
        ),
        migrations.CreateModel(
            name='Carpenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Carpenter groups',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.PositiveIntegerField(unique=True)),
                ('current_uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_weekends', models.BooleanField()),
                ('num_of_carpenters', models.IntegerField()),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('built', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previously_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpenters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpenters', to='workload.carpenters')),
            ],
            options={
                'verbose_name_plural': 'Carpenters',
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.AddField(
            model_name='carpenters',
            name='custom_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpenter_groups', to='workload.custominput'),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(unique=True)),
                ('order_number', models.CharField(max_length=20)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('dry_hire', models.CharField(max_length=3)),
                ('dry_hire_transport', models.CharField(max_length=3)),
                ('status', models.IntegerField()),
                ('status_name', models.CharField(max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('load_starts_at', models.DateTimeField(blank=True, null=True)),
                ('load_ends_at', models.DateTimeField(blank=True, null=True)),
                ('deliver_starts_at', models.DateTimeField(blank=True, null=True)),
                ('deliver_ends_at', models.DateTimeField(blank=True, null=True)),
                ('setup_starts_at', models.DateTimeField(blank=True, null=True)),
                ('setup_ends_at', models.DateTimeField(blank=True, null=True)),
                ('show_starts_at', models.DateTimeField(blank=True, null=True)),
                ('show_ends_at', models.DateTimeField(blank=True, null=True)),
                ('takedown_starts_at', models.DateTimeField(blank=True, null=True)),
                ('takedown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('collect_starts_at', models.DateTimeField(blank=True, null=True)),
                ('collect_ends_at', models.DateTimeField(blank=True, null=True)),
                ('unload_starts_at', models.DateTimeField(blank=True, null=True)),
                ('unload_ends_at', models.DateTimeField(blank=True, null=True)),
                ('weight_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previously_updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='workload.client')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='custominput',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_input', to='workload.opportunity'),
        ),
        migrations.AddField(
            model_name='carpenters',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpenter_groups', to='workload.opportunity'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.PositiveIntegerField(unique=True)),
                ('current_uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('bookable', models.BooleanField(default=False)),
                ('membership_id', models.PositiveIntegerField()),
                ('membership_type', models.CharField(max_length=50)),
                ('lawful_basis_id', models.PositiveIntegerField()),
                ('lawful_basis_type_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='owners', to='workload.tag')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='workload.owner'),
        ),
        migrations.CreateModel(
            name='ScenicCalcItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_item_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_working_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previously_updated_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenic_calc_items', to='workload.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Scenic calc item groups',
            },
        ),
        migrations.CreateModel(
            name='ScenicCalcItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField()),
                ('opportunity_id', models.IntegerField()),
                ('current_item_id', models.IntegerField()),
                ('current_item_type', models.CharField(max_length=10)),
                ('opportunity_item_type', models.IntegerField()),
                ('opportunity_item_type_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('previous_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previously_updated_at', models.DateTimeField(blank=True, null=True)),
                ('scenic_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workload.sceniccalcitems')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='workload.tag'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='workload.tag'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='workload.venue'),
        ),
    ]
