# Generated by Django 5.0.13 on 2025-10-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sceniccalcitems',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sceniccalcitems',
            name='previous_grand_total',
        ),
        migrations.RemoveField(
            model_name='sceniccalcitems',
            name='previous_working_days',
        ),
        migrations.RemoveField(
            model_name='sceniccalcitems',
            name='working_days',
        ),
        migrations.AddField(
            model_name='custominput',
            name='previous_working_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='working_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ScenicCalcTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previously_updated_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenic_calc_total', to='workload.opportunity')),
            ],
        ),
    ]
