# Generated by Django 5.0.13 on 2025-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_opportunity_previous_collect_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominput',
            name='previous_planned_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='previous_start_build_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='start_build_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
