# Generated by Django 5.0.13 on 2025-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_custominput_previous_planned_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominput',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='previous_date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='previous_time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
