# Generated by Django 5.0.13 on 2025-10-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_custominput_date_out_custominput_previous_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproducts',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
