# Generated by Django 5.0.13 on 2025-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_alter_activeproducts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominput',
            name='previous_include_weekends',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominput',
            name='previous_num_of_carpenters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
