# Generated by Django 5.0.13 on 2026-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0007_custominput_previous_include_weekends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sceniccalcitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sceniccalcitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
