# Generated by Django 5.0.13 on 2026-01-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0008_opportunity_is_active_sceniccalcitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceniccalctotal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
